In [1]:
import pandas as pd
import numpy as np
from util import modelhelper

In [2]:
confirmed_vs_mobility = pd.read_csv('conf_vs_mob_ID.csv')

In [3]:
sr1_code = ''
loc_key = "ID" + ("_" if sr1_code != '' else "") + sr1_code
ndays = 7
lcc_colname = 'LEAD_%dDAYS' % (ndays)

In [4]:
covid_X = confirmed_vs_mobility[['CUMULATIVE_CONFIRMED', 'MOBILITY_RETAIL_AND_RECREATION']]
covid_y = confirmed_vs_mobility[lcc_colname]

covid_X = np.array(covid_X.values.tolist())
covid_y = np.array(covid_y.values.tolist())

n_null = ndays * -1

covid_X_unknown = covid_X[n_null:] # Save null y from X dataset

# Bersihkan dari nilai null
covid_X = covid_X[:n_null]
covid_y = covid_y[:n_null]

In [5]:
repo = modelhelper.get_model_above_threshold(covid_X, covid_y, 0.1, 0.4)

In [6]:
repo.r2_score()

0.9997774137322253

In [9]:
repo.predict([[257388, -23]])

array([287715.33551384])

In [14]:
new_data = pd.read_csv('bq-results-20201203-213718-upug5frc8z61.csv')

In [15]:
new_data_loc_id = new_data.loc[new_data.location_key == 'ID']

In [16]:
new_data_loc_id[['date','location_key','cumulative_confirmed', 'mobility_retail_and_recreation']][:20]

date location_key  cumulative_confirmed  \
244  2020-10-01           ID              291182.0   
245  2020-10-02           ID              295499.0   
246  2020-10-03           ID              299506.0   
247  2020-10-04           ID              303498.0   
248  2020-10-05           ID              307120.0   
249  2020-10-06           ID              311176.0   
250  2020-10-07           ID              315714.0   
251  2020-10-08           ID              320564.0   
252  2020-10-09           ID              324658.0   
253  2020-10-10           ID              328952.0   
254  2020-10-11           ID              333449.0   
255  2020-10-12           ID              336716.0   
256  2020-10-13           ID              340622.0   
257  2020-10-14           ID              344749.0   
258  2020-10-15           ID              349160.0   
259  2020-10-16           ID              353461.0   
260  2020-10-17           ID              357762.0   
261  2020-10-18           ID              361867.0   
262  2020-10-19           ID              365240.0   
263  2020-10-20           ID              368842.0   

     mobility_retail_and_recreation  
244                           -20.0  
245                           -20.0  
246                           -19.0  
247                           -20.0  
248                           -17.0  
249                           -19.0  
250                           -18.0  
251                           -18.0  
252                           -20.0  
253                           -22.0  
254                           -19.0  
255                           -17.0  
256                           -19.0  
257                           -16.0  
258                           -16.0  
259                           -20.0  
260                           -17.0  
261                           -19.0  
262                           -20.0  
263                           -19.0

In [17]:
repo.predict([[299506.0, -19.0]])

array([334444.2228466])

In [18]:
324658.0 - 334301.1040636

-9643.10406360001

In [19]:
repo.predict([[400.0, -19.0]])

array([2811.68530358])

In [20]:
repo.get_model().coef_

array([1.10874585, 7.68235869])

In [21]:
repo.predict([[400, -100]])

array([2189.41424955])

In [24]:
repo.rmse()

1146.0746656374458